### ISSUE TITLE
Nice to have: API access to cookies in jar

### ISSUE THREAD

**Issue by jjw** [brynary/rack-bug#11]
When testing apps that set cookie options it would be nice to have access to the individual cookies in the jar.  I can't see any API to do this.  `Rack::Test::CookieJar#[]` and `#for(uri)` return the raw value, not the underlying `Rack::Test::Cookie`, and `#hash_for()` is protected.  Would it be okay to un-protect `#hash_for()` or perhaps provide a  simple `attr_reader :cookies` within `Rack::Test::CookieJar` please?

**Comment by lukemelia** [comment]
Seems like this issue might belong to Rack::Test, not Rack::Bug. Please reopen if I am mistaken.

**Comment by jjw** [comment]
Yes, sorry; don't recall why I thought it was a Rack::Bug issue.  Guess I was using R::B for something at the time.  Thanks,  Jerry
