### ISSUE TITLE
rack-bug for production server

### ISSUE THREAD

**Issue by ctrochalakis** [brynary/rack-bug#12]
Is is considered ok to use rack-bug on production environments? Is there a performance penalty?

Those could be useful additions to the readme file

**Comment by lukemelia** [comment]
Added a section to the readme. Performance depends in large part on what panels are enabled. We've found that performance overhead is high enough that we don't run it regularly, but we are OK adding it to production for a few hours here and there for troubleshooting or performance evaluation.
