### ISSUE TITLE
Errors trying to run specs

### ISSUE THREAD

**Issue by zbelzer** [brynary/rack-bug#14]
After removing "check_dependencies" and installing rack-test, sinatra and webrat I was able to kick off the spec tests, but I only get "undefined method `upcase' for :cookie:Symbol" Is this defined in another gem? A different version perhaps?

I only removed check_dependencies since rake said it wasn't defined (and it isn't in the Rakefile) but maybe there's some gem I'm missing from the outset that defines it. Who knows. If it actually worked, maybe it what have told me what I was missing.

Thanks.

**Comment by knzai** [comment]
I don't have them all running yet, but: http://github.com/timocratic/rack-bug/commit/40306c5035baf449352c512d860b9df3003bfb1c

**Comment by lukemelia** [comment]
Fixed. with 0.3.0
