### ISSUE TITLE
Rack::Bug toolbar is not displayed in Google Chrome on OS X

### ISSUE THREAD

**Issue by lwille** [brynary/rack-bug#15]
The toolbar is not displayed in the application using Chrome 5.0.307.9 beta on OS X.
When opening bookmarklet.html, the toolbar is rendered correctly.
It looks like the toolbar's markup is not inserted at the end of the page when opened via Chrome.

Oddly enough, it works well in Safari - which is also a Webkit browser.

**Comment by fugufish** [comment]
+1

**Comment by lukemelia** [comment]
Works for me with latest Rack::Bug and latest Chrome on OS X (5.0.375.55)
