### ISSUE TITLE
Hoptoad deprecated environment_filters

### ISSUE THREAD

**Issue by kunzmann** [brynary/rack-bug#18]
"config.environment_filters has been deprecated and has no effect." as of version 2.0.19 of hoptoad_notifier

I'm not sure if this affects rack-bug, but the README could be updated.

**Comment by lukemelia** [comment]
Thanks. Removed it from the README. No specific hoptoad configuration is necessary.

**Comment by mpoisot** [comment]
The deprecated hoptoad config is still mentioned in the wiki root page.
