### ISSUE TITLE
rake spec:plugins fail on a new rails application

### ISSUE THREAD

**Issue by unders** [brynary/rack-bug#3]
(in .../vendor/plugins/rack-bug)
    /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- rack/test (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/unders/homerails/qwert/vendor/plugins/rack-bug/spec/spec_helper.rb:4

**Comment by yaroslav** [comment]
you'll need to install the rack-test gem, I believe. that is pretty common for rack stack.

**Comment by unders** [comment]
Thanks for the information; It would be nice it that dependency was added to the readme file.

**Comment by zbelzer** [comment]
I seemed to need webrat and sinatra in order to get things going. 'check_dependencies' seemed to be required, but not defined. Not sure what that's about.

**Comment by lukemelia** [comment]
Fixed as of 0.3.0
