### ISSUE TITLE
Please add gemspec

### ISSUE THREAD

**Issue by alexgorbatchev** [brynary/rack-bug#4]
Make a gem please... pretty please... with sugar on top (or coke, please underline preferred).

**Comment by DefV** [comment]
I second this request - I don't like development stuff be in plugins

**Comment by levifig** [comment]
There's a gem already: http://gemcutter.org/gems/rack-bug
Add "http://gemcutter.org" to your RubyGems sources! ;)

**Comment by lukemelia** [comment]
There's an up-to-date gem.
