### ISSUE TITLE
Rack::Bug conflicts with Hoptoad Notifier

### ISSUE THREAD

**Issue by yaroslav** [brynary/rack-bug#6]
Guys, R::B is currently not recommended to use on production. Really.

It breaks hoptoad notifier at this very moment.

I still use it on development — be sure to enable it in your initializers only if Rails.env.development?

I have absolutely NO idea what can be causing this. Feedback welcome.

**Comment by lukemelia** [comment]
Added a note to the README with a solution to this issue in 60eec0706cdda25479c8a5830062ca7ab2313a7b
