### ISSUE TITLE
Unable to see rack-bug toolbar

### ISSUE THREAD

**Issue by larrywright** [brynary/rack-bug#8]
I've installed the plugin using the instructions and everything looks ok. I can go to http://localhost:3000/**rack_bug**/bookmarklet.html and install the bookmarklet fine. When I click on it, it prompts me for the password (I don't have one), and then it says it's enabled. The problem is I never see the toolbar on any of my application's pages. I _can_ see it when I go back to the bookmarklet page, but that is all.

It may be something weird about my config but I don't know where to start looking. Any suggestions?

**Comment by lukemelia** [comment]
If you view source, can you see it in the HTML (at the end of the page)? It may be a CSS conflict of some sort.

**Comment by handerpeder** [comment]
Are you using iframes on your pages. rack-bug inserts its render code just before the first </body> tag found. This means that the rack-bug code gets inserted in the wrong place and doesn't display the toolbar. I've made an easy fix to this which is available in my fork: http://github.com/handerpeder/rack-bug/tree/master

**Comment by larrywright** [comment]
Sorry - missed the first reply here on the 4th. No, I don't see it when I view source at all. I do not use any iframes.

**Comment by handerpeder** [comment]
hmm. are you sure the rack-bug code is being run? try adding a log statement/breakpoint in there and check if it's triggered. If it is then check that 
"if toolbar_requested? && ip_authorized? && password_authorized?" is evaluated to true in toolbar.rb.

**Comment by ujh** [comment]
I had to set the ip_masks to the following to make it work: 

```
[IPAddr.new("127.0.0.1"), IPAddr.new("::1")]
```

**Comment by sumangurung** [comment]
I also couldn't see the toolbar in firefox but i could see the toolbar in opera, weird!!
I also tried setting the ip_masks, but i get 'uninitialized constant IPAddr'. Am i missing some extra configuration???

**Comment by deime** [comment]
I had exactly the same problem. One of my "after_filter" is compressing the server response, and disabling it resolves the problem.

**Comment by ippa** [comment]
same problem here, on rails 2.3.6 and latest firefox

**Comment by larrywright** [comment]
The root cause of this, oddly enough, was that I had a malformed html document - it had no body tag (due to a stupid error in my Haml template). rack-bug inserts the toolbar at the top of the document body, and so when it doesn't exist it can't insert the toolbar.

Stupid error on my part, masked by the fact that browsers are quite content to render html without a body tag. It might be helpful to have rack-bug log a warning in the event that the body tag can't be found. If I have the time, I will add this and send a pull request.

**Comment by dropwhile** [comment]
larrywright, you saved me. I was having the _exact_ same problem. I was rendering a markdown template without body tags, and the toolbar wasn't showing. 

Adding the tags made it work fine. _slaps forehead_

**Comment by larrywright** [comment]
cactus, glad that helped - it took me waaaay too long to figure that out.
